// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWbO98QjfzLpwi5mo5WuYJ1bfNuy-wehw',
    appId: '1:262984157915:web:dddcd93aceff01afc29afe',
    messagingSenderId: '262984157915',
    projectId: 'io-mom-iot',
    authDomain: 'io-mom-iot.firebaseapp.com',
    storageBucket: 'io-mom-iot.firebasestorage.app',
    measurementId: 'G-EVVCHD373X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE5Ye9iAP1VFmO3WgNCEVv2M8VKx1KSTE',
    appId: '1:262984157915:android:f32b6a7ea53ad711c29afe',
    messagingSenderId: '262984157915',
    projectId: 'io-mom-iot',
    storageBucket: 'io-mom-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsyqbHYfx7v7y2WY1rAgD3-QZ314jxgZ4',
    appId: '1:262984157915:ios:4fbdcfaf51e89b3cc29afe',
    messagingSenderId: '262984157915',
    projectId: 'io-mom-iot',
    storageBucket: 'io-mom-iot.firebasestorage.app',
    iosClientId: '262984157915-9t5iof7jss8sou14ttcncirqhb4eqkk8.apps.googleusercontent.com',
    iosBundleId: 'my.edu.tarumt.ioMom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsyqbHYfx7v7y2WY1rAgD3-QZ314jxgZ4',
    appId: '1:262984157915:ios:4fbdcfaf51e89b3cc29afe',
    messagingSenderId: '262984157915',
    projectId: 'io-mom-iot',
    storageBucket: 'io-mom-iot.firebasestorage.app',
    iosClientId: '262984157915-9t5iof7jss8sou14ttcncirqhb4eqkk8.apps.googleusercontent.com',
    iosBundleId: 'my.edu.tarumt.ioMom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWbO98QjfzLpwi5mo5WuYJ1bfNuy-wehw',
    appId: '1:262984157915:web:a7d43dc979c8ef13c29afe',
    messagingSenderId: '262984157915',
    projectId: 'io-mom-iot',
    authDomain: 'io-mom-iot.firebaseapp.com',
    storageBucket: 'io-mom-iot.firebasestorage.app',
    measurementId: 'G-YJ7V8CW594',
  );
}
